name: Seek and mark ci

on:
  push:
    branches:
      - seekAndMark
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Check style
        run: npm run lint
      - name: Check build
        run: npm run build
